Handling and parsing the getopt errors

diff --git a/run b/run
--- a/run
+++ b/run
@@ -191,6 +191,14 @@ do
 done
 
 optstring=$optstring"D:"
+err=$(getopt $optstring $ARGV 2>&1 > /dev/null)
+if [ $(is_empty "$err") != "true" ]; then
+  cat >&2 <<EOF
+Error: You're passing the invalid option -$(sed "s/.*'\(.*\)'/\1/" <<< $err) to the script
+EOF
+  exit 1
+fi
+
 args=`getopt $optstring $ARGV`
 eval set -- "$args"
 
